/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ionic_Msmq_Queue_Access */

#ifndef _Included_ionic_Msmq_Queue_Access
#define _Included_ionic_Msmq_Queue_Access
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
