/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ionic_Msmq_Queue */

#ifndef _Included_ionic_Msmq_Queue
#define _Included_ionic_Msmq_Queue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ionic_Msmq_Queue
 * Method:    nativeInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ionic_Msmq_Queue_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     ionic_Msmq_Queue
 * Method:    nativeCreateQueue
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_ionic_Msmq_Queue_nativeCreateQueue
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     ionic_Msmq_Queue
 * Method:    nativeDeleteQueue
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ionic_Msmq_Queue_nativeDeleteQueue
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ionic_Msmq_Queue
 * Method:    nativeOpenQueue
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ionic_Msmq_Queue_nativeOpenQueue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ionic_Msmq_Queue
 * Method:    nativeOpenQueueForSend
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ionic_Msmq_Queue_nativeOpenQueueForSend
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ionic_Msmq_Queue
 * Method:    nativeOpenQueueForReceive
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ionic_Msmq_Queue_nativeOpenQueueForReceive
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ionic_Msmq_Queue
 * Method:    nativeSend
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_ionic_Msmq_Queue_nativeSend
  (JNIEnv *, jobject, jstring, jint, jstring, jstring, jint);

/*
 * Class:     ionic_Msmq_Queue
 * Method:    nativeReceiveBytes
 * Signature: (Lionic/Msmq/Message;II)I
 */
JNIEXPORT jint JNICALL Java_ionic_Msmq_Queue_nativeReceiveBytes
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     ionic_Msmq_Queue
 * Method:    nativeSendBytes
 * Signature: ([BLjava/lang/String;[BIZ)I
 */
JNIEXPORT jint JNICALL Java_ionic_Msmq_Queue_nativeSendBytes
  (JNIEnv *, jobject, jbyteArray, jstring, jbyteArray, jint, jboolean);

/*
 * Class:     ionic_Msmq_Queue
 * Method:    nativeClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ionic_Msmq_Queue_nativeClose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
